# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Notes
email: 
description: > # this means to ignore newlines until "baseurl:"
        This site publishes some of my daily notes. 
baseurl: "/Notes" # the subpath of your site, e.g. /blog
url: "https://schfan.github.io/Notes/" # the base hostname & protocol for your site
github_username:  schfan

# Build settings
markdown: redcarpet
